name: flutter_demo_3d
description: A simple Wavefront 3D object renderer in Flutter

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/brain.obj
    - assets/brain.mtl

  uses-material-design: true